### ISSUE TITLE
State what IAM roles are needed for this tool to function

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-api-dicom-fuse#15]
I  think Healthcare DICOM Editor is all that is needed?

Should be in the README.

**Comment by arvgord** [comment]
I'm a bit confused. I've found that: 
- Healthcare DICOM Administrator can view DICOM Stores but can't open it(I get 403 Error).
- Healthcare DICOM Editor can open DICOM Stores, Study, and Series, upload Instances but can't delete Instances(I get 403 Error).
- Service account with both roles can open all and can delete Instances.

**Comment by dzelemba** [comment]
An explanation of what permissions each roles gives is here:  https://cloud.google.com/healthcare/docs/concepts/access-control#roles.

We are planning on adding the delete permission to DICOM Editor.

What do you mean by "...can view DICOM Stores but can't open it". You should be able to list and view DICOM Stores, but Admin does *not* give access to the actual data which is expected. We're going to rename this role to "Healthcare DICOM Store Administrator" to make that more clear.

**Comment by arvgord** [comment]
> What do you mean by "...can view DICOM Stores but can't open it". 

I mean that I can view a list of folders in chosen Dataset but I can't open any DICOM Store folder.

**Comment by arvgord** [comment]
Ok, I'll add about DICOM Editor role in README.md
