### ISSUE TITLE
Output HTTP error body for STOW error

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-api-dicom-fuse#20]
Right now the logs show:

```
com.google.dicomwebfuse.exception.DicomFuseException: Failed to upload - dicom/UID.dcm!HTTP/1.1 409 Conflict https://healthcare.googl
eapis.com/v1beta1/projects/<project>/locations/us-central1/datasets/<dataset>/dicomStores/<dicomStore>/dicomWeb/studies/
```

But the error body has more useful information about what kind of error it is (invalid DICOM file vs. already exists), so we should print that as well.

**Comment by arvgord** [comment]
If we upload a file and the file exist on the server, the file will be uploaded without any error. I've tested it. But if we have different files on the server and client-side(with same study, series, and instance ID) we will get 409 Conflict error.

**Comment by dzelemba** [comment]
Yes that is correct. You'll also get a 409 conflict error if you try and upload an invalid DICOM file, so it'd be good to add the error body to be able to tell which one it is.

**Comment by pavertomato** [comment]
should it be formatted for pretty output? without formatting it's quite unreadable 
![image](https://user-images.githubusercontent.com/878990/64528949-e9c05680-d333-11e9-8966-f87f043a17f4.png)
for formatting i suggest to use https://jsoup.org/ with MIT license, is it ok?

**Comment by dzelemba** [comment]
Yeah pretty output would be nice. jsoup is fine but note that the response isn't actually HTML, it's XML.

**Comment by pavertomato** [comment]
![image](https://user-images.githubusercontent.com/878990/64602271-aecc2a80-d3e8-11e9-9b2e-9ce064986772.png)
