### ISSUE TITLE
Support passing in extra mount options

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-api-dicom-fuse#21]
gcsfuse supports the -o flag which you can pass extra mount options through, e.g.

`gcsfuse -o allow_other`

Which allows other users to access this mount. We should support the same option in DICOMfuse.

**Comment by arvgord** [comment]
I will add the ability to add mount options when a user starts DICOMFuse.

**Comment by arvgord** [comment]
What do you think, if I will add the option like `--extraMountOptions allow_other,entry_timeout=0,attr_timeout=0,etc`? And users will be able to add a list of options.

**Comment by dzelemba** [comment]
Sounds good to me!
