### ISSUE TITLE
Clarify study/series limit in README

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-api-dicom-fuse#22]
Looks like (https://github.com/GoogleCloudPlatform/healthcare-api-dicom-fuse/blob/75adf49c64207266420efb090633e471c81d9f85/src/main/java/com/google/dicomwebfuse/dao/Constants.java#L36) we currently limit the number of studies we can show in a folder to 5000. But we don't document that in the README.

**Comment by arvgord** [comment]
https://github.com/GoogleCloudPlatform/healthcare-api-dicom-fuse/blob/75adf49c64207266420efb090633e471c81d9f85/src/main/java/com/google/dicomwebfuse/dao/Constants.java#L38-L40
The current implementation supports 15,000 results in folders for study, series and instances. This was mentioned in the [README.md - Notes](https://github.com/GoogleCloudPlatform/healthcare-api-dicom-fuse#mount-options). In the current case, it was a bug in DICOMFuse code (incorrect start offset). 
https://github.com/GoogleCloudPlatform/healthcare-api-dicom-fuse/blob/75adf49c64207266420efb090633e471c81d9f85/src/main/java/com/google/dicomwebfuse/dao/FuseDaoImpl.java#L135
I've created PR to fix this.

**Comment by dzelemba** [comment]
Moving bug out into its own issue. Closing this issue as the README does state the correct limit.
