### ISSUE TITLE
Upgrade Jackson Dependency

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-api-dicom-fuse#31]
https://github.com/GoogleCloudPlatform/healthcare-api-dicom-fuse/network/alert/pom.xml/com.fasterxml.jackson.core:jackson-databind/open

Upgrade com.fasterxml.jackson.core:jackson-databind to version 2.9.10 or later.

**Comment by arvgord** [comment]
Done

**Comment by dzelemba** [comment]
New alert: upgrade to 2.9.10.1

**Comment by arvgord** [comment]
Updated
