### ISSUE TITLE
Creating DICOM Stores in DICOMFuse

### ISSUE THREAD

**Issue by arvgord** [GoogleCloudPlatform/healthcare-api-dicom-fuse#35]
@dzelemba What do you think if I'll add a feature to create a DICOM Store through creating folders in DICOMFuse?

**Comment by dzelemba** [comment]
Sounds good to me!

**Comment by dzelemba** [comment]
To support the graphical UI in Windows/Mac. We could support the rename operation by deleting the old dicom store and creating a new one? We would just have to check that the dicom store is empty.

**Comment by arvgord** [comment]
I think I can implement this feature. I'm investigating this.

**Comment by arvgord** [comment]
Done. Also, I can add delete DICOM Store operation. What do you think about it?

**Comment by dzelemba** [comment]
Nice, thanks! Let's ignore deletion until we have a use case for it.
